dist: trusty

language: php

sudo: required

php:
  - 5.6
  - 7.0
  - 7.1
#  - 7.2
#  - 7.3

env:
  - WP_VERSION=latest WP_MULTISITE=0 PHP_LATEST_STABLE=7.1

matrix:
  include:
  - php: 5.6
    env: WP_VERSION=latest WP_MULTISITE=1 PHP_LATEST_STABLE=7.1
  - php: 5.4
    env: WP_VERSION=5.1.1 WP_MULTISITE=0 PHP_LATEST_STABLE=7.1

before_install:
  - npm i npm@latest -g
  - chmod +x docker-compose.yml
  - docker-compose --version
  - sudo docker-compose up -d
  - sudo chmod 777 -R ~/wordpress_data/

before_script:
  - phpenv config-rm xdebug.ini
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - bash tests/bin/install.sh give_test root '' localhost $WP_VERSION
  - bash tests/bin/travis.sh before

script:
  - phpunit -c phpunit.xml
  - bash tests/e2e/bin/install.sh

after_script:
  - bash tests/bin/travis.sh after
