language: php

sudo: false

php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
- hhvm

env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=4.5 WP_MULTISITE=0
- WP_VERSION=4.4 WP_MULTISITE=0
- WP_VERSION=4.3 WP_MULTISITE=0

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
- bash tests/bin/install.sh wordpress_test root '' localhost $WP_VERSION
- bash tests/bin/travis.sh before
- composer install

script: phpunit -c phpunit.xml

after_script:
- bash tests/bin/travis.sh after

notifications:
 slack: givewp:AgWxvdTjTkSjd8FHM5ndeSH5