language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0 PHP_LATEST_STABLE=7.1

matrix:
  include:
  - php: 5.6
    env: WP_VERSION=latest WP_MULTISITE=1 PHP_LATEST_STABLE=7.1
  - php: 5.3
    env: WP_VERSION=latest WP_MULTISITE=0 PHP_LATEST_STABLE=7.1
    dist: precise

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - bash tests/bin/install.sh give_test root '' localhost $WP_VERSION
  - bash tests/bin/travis.sh before

script:
  - phpunit -c phpunit.xml

after_script:
  - bash tests/bin/travis.sh after