name: Build Plugin Pre-Release

on:
    release:
        types: [ prereleased ]

jobs:
    build:
        uses: impress-org/givewp-github-actions/.github/workflows/pre-release.yml@master
        with:
            plugin_slug: give-next-gen
            zip_name: give-next-gen
